# Generated by Django 6.0.7 on 2026-07-19 09:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollment',
            name='grade',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True, validators=[django.core.validators.MinValueValidator(0, message='Grade must be 0 or greater'), django.core.validators.MaxValueValidator(4.0, message='Grade cannot exceed 4.0')]),
        ),
        migrations.AlterUniqueTogether(
            name='enrollment',
            unique_together={('student', 'grade')},
        ),
    ]
